Vocantas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vocantas.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

Vocantas/Controllers/TvmazeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VocantsBusinessLogic.Interface;
using VocantsBusinessLogic.Models;
using VocantsBusinessLogic.Manager;

namespace Vocantas.Controllers
{
    public class TvmazeController : Controller
    {
		private readonly ITvMazeManager _TvMazeManager;
		public TvmazeController(ITvMazeManager TvMazeManager)
		{
			_TvMazeManager = TvMazeManager;
		}
		public TvmazeController()
		{
			_TvMazeManager = new TvMazeManager();
		}

		// GET: Tvmaze
		public ActionResult Index()
        {
            return View();
        }

		public ActionResult Serverside()
		{
			
			var result = _TvMazeManager.GetData();

			return View(result);	
		}
		public ActionResult Clientside()
		{
			return View();
		}
		[HttpPost]
		public ActionResult Clientside(FormCollection fc)
		{
			return View();
		}
	}
}

Vocantas/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vocantas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vocantas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Vocantas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
			<div class="navbar-header">
				<img src="https://uploads-ssl.webflow.com/58d9a73573d457b0092488c8/59079c4270fa5a7feb540a00_logo-hi-res-blue.png" alt="" class="header-logo">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
			</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ServerSide", "Serverside", "Tvmaze")</li>
                    <li>@Html.ActionLink("ClientSide", "Clientside", "Tvmaze")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Vocantas/Views/Tvmaze/Clientside.cshtml
@{
	ViewBag.Title = "Clientside";
}

<h2>Clientside</h2>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			@using (Html.BeginForm("Tvmaze", "Upload", FormMethod.Post,
												  new { enctype = "multipart/form-data", @class = "form-horizontal" }))
			{
				@Html.ValidationSummary(true)
				<div class="row form-group">
					<div class="col-md-3">
						@Html.Label("Name")
					</div>
					<div class="col-md-6">
						<input type="text" class="form-control" id="name" />
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						@Html.Label("Genre")
					</div>
					<div class="col-md-6">
						<input type="text" class="form-control" id="genre" />
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						@Html.Label("PremieredOn")
					</div>
					<div class="col-md-6">
						<input type="date" class="form-control" id="primieredOn" />
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						@Html.Label("Rating")
					</div>
					<div class="col-md-6">
						<input type="text" class="form-control" id="rating" />
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						@Html.Label("Summary")
					</div>
					<div class="col-md-6">
						<input type="text" class="form-control" id="summary" />
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						@Html.Label("Inserted")
					</div>
					<div class="col-md-6">
						<input type="datetime" class="form-control" id="inserted" />
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<input type="submit" class="btn btn-primary" />
						</div>
				</div>
			}
		</div>
	</div>
</div>


<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
	var uri = 'http://api.tvmaze.com/shows/42';

	$(document).ready(function () {

		$.get(uri).done(function (data) {
			$("#name").val(data.name);
			$("#genre").val(data.genre[0]);
			$("#primieredOn").val(data.premiered);
			$("#rating").val(data.rating);
			$("#summary").val(data.summary);
			$("#inserted").val(data.updated);
		});
	});

</script>

Vocantas/Views/Tvmaze/Serverside.cshtml
@model IEnumerable<VocantsBusinessLogic.Models.TvMazeViewModel>

@{
    ViewBag.Title = "Serverside - Part1";
}

<h2>Serverside - Part1</h2>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-bordered">
					<tr>
						<th>Genres</th>
						<th>Name</th>
						<th>Premiered</th>
						<th>Rating</th>
						<th>Summary</th>
					</tr>
					@foreach (var d in Model)
					{
					<tr>
						<td>@d.Name</td><td>@d.Genres</td>
						<td>@d.Premiered</td><td>@d.Rating</td><td>@Html.Raw(d.Summary)</td>
					</tr>
					}
				</table>

			</div>
		</div>
	</div>

</div>